# Generated by Django 5.2.1 on 2025-05-12 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('Estrela', 'ESTRELA'), ('GALÁXIA', 'Galáxia'), ('Planeta', 'PLANETA')], default='', max_length=100),
        ),
    ]
